version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hotel-kusum-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_kusum_db
      MYSQL_USER: hotelkusum
      MYSQL_PASSWORD: hotelkusum
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d  # For initial SQL scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  # NestJS Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hotel-kusum-nest-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=hotelkusum
      - DATABASE_PASSWORD=hotelkusum
      - DATABASE_NAME=hotel_kusum_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
